syntax = "proto3";

package echo;

option go_package = "./echo";

service EchoService {
  rpc Echo (EchoRequest) returns (EchoResponse) {}
}

message EchoRequest {
  string message = 1;
}

message EchoResponse {
  string message = 1;
} 

service MathService {
  rpc Add(NumbersRequest) returns (NumberResponse) {}
  rpc Subtract(NumbersRequest) returns (NumberResponse) {}
  rpc Multiply(NumbersRequest) returns (NumberResponse) {}
  rpc Divide(NumbersRequest) returns (NumberResponse) {}
}

message NumbersRequest {
  double a = 1;
  double b = 2;
}

message NumberResponse {
  double result = 1;
}