// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumbersRequest) Reset() {
	*x = NumbersRequest{}
	mi := &file_proto_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersRequest) ProtoMessage() {}

func (x *NumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumbersRequest.ProtoReflect.Descriptor instead.
func (*NumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{2}
}

func (x *NumbersRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *NumbersRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

type NumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	mi := &file_proto_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{3}
}

func (x *NumberResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_echo_proto protoreflect.FileDescriptor

const file_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/echo.proto\x12\x04echo\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x0eNumbersRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\"(\n" +
	"\x0eNumberResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2>\n" +
	"\vEchoService\x12/\n" +
	"\x04Echo\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\"\x002\xee\x01\n" +
	"\vMathService\x123\n" +
	"\x03Add\x12\x14.echo.NumbersRequest\x1a\x14.echo.NumberResponse\"\x00\x128\n" +
	"\bSubtract\x12\x14.echo.NumbersRequest\x1a\x14.echo.NumberResponse\"\x00\x128\n" +
	"\bMultiply\x12\x14.echo.NumbersRequest\x1a\x14.echo.NumberResponse\"\x00\x126\n" +
	"\x06Divide\x12\x14.echo.NumbersRequest\x1a\x14.echo.NumberResponse\"\x00B\bZ\x06./echob\x06proto3"

var (
	file_proto_echo_proto_rawDescOnce sync.Once
	file_proto_echo_proto_rawDescData []byte
)

func file_proto_echo_proto_rawDescGZIP() []byte {
	file_proto_echo_proto_rawDescOnce.Do(func() {
		file_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)))
	})
	return file_proto_echo_proto_rawDescData
}

var file_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),    // 0: echo.EchoRequest
	(*EchoResponse)(nil),   // 1: echo.EchoResponse
	(*NumbersRequest)(nil), // 2: echo.NumbersRequest
	(*NumberResponse)(nil), // 3: echo.NumberResponse
}
var file_proto_echo_proto_depIdxs = []int32{
	0, // 0: echo.EchoService.Echo:input_type -> echo.EchoRequest
	2, // 1: echo.MathService.Add:input_type -> echo.NumbersRequest
	2, // 2: echo.MathService.Subtract:input_type -> echo.NumbersRequest
	2, // 3: echo.MathService.Multiply:input_type -> echo.NumbersRequest
	2, // 4: echo.MathService.Divide:input_type -> echo.NumbersRequest
	1, // 5: echo.EchoService.Echo:output_type -> echo.EchoResponse
	3, // 6: echo.MathService.Add:output_type -> echo.NumberResponse
	3, // 7: echo.MathService.Subtract:output_type -> echo.NumberResponse
	3, // 8: echo.MathService.Multiply:output_type -> echo.NumberResponse
	3, // 9: echo.MathService.Divide:output_type -> echo.NumberResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_echo_proto_init() }
func file_proto_echo_proto_init() {
	if File_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_echo_proto_goTypes,
		DependencyIndexes: file_proto_echo_proto_depIdxs,
		MessageInfos:      file_proto_echo_proto_msgTypes,
	}.Build()
	File_proto_echo_proto = out.File
	file_proto_echo_proto_goTypes = nil
	file_proto_echo_proto_depIdxs = nil
}
